build:
  environment:
    php: 8.0
  dependencies:
    override:
      - composer install --prefer-dist --no-interaction --no-progress --no-suggest
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
          coverage:
            file: coverage.clover
            format: clover

filter:
  paths: ["app/*"]


