build:
  environment:
    php: 8.0
  dependencies:
    override:
      - composer install --prefer-dist --no-interaction --no-progress --no-suggest
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths: ["app/*"]

tools:
  external_code_coverage:
    timeout: 600


