language: php

php:
  - 7.4

services:
  - mysql

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-progress --no-suggest ${COMPOSER_FLAGS}
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
