version: '3'
services:

  ### WEB: Web server #################################################
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
      args:
        - DOCKER_SSHAM_UID=${DOCKER_SSHAM_UID:-1000}
    volumes:
      - ./:/var/www:ro
    ports:
      - "80:80"
    depends_on:
      - app

  ### APP: Application server #########################################
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        - DOCKER_SSHAM_UID=${DOCKER_SSHAM_UID:-1000}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=database
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
    ports:
      - "9000:9000"
    depends_on:
      - database

  ### DATABASE: Database server #############################################
  database:
    image: 'mysql/mysql-server:8.0'
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'verysecret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  ### SSH-SERVER: SSH server ################################################
  ssh-server:
    build:
      context: ./
      dockerfile: docker/ssh/Dockerfile
    ports:
      - "2201:22"
    depends_on:
      - app

volumes:
  db-data:
    driver: local

