baseURL = 'https://ssham.pacoorozco.info/'
languageCode = 'en-us'
title = 'ssham: Secure Shell Access Manager'

theme = "hugo-geekdoc"

enableRobotsTXT = true

[params]
    geekdocLogo = "logo-small.png"

