name: Release version
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        id: build_project
        env:
          DIST_FILE: ./dist/ssham-dist-${{ github.ref_name }}
        run: |
          composer archive --format=zip --file=$DIST_FILE
          echo "DIST_FILE=${DIST_FILE}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: ${{ steps.build_project.outputs.DIST_FILE }}.zip
          artifactContentType: application/zip
          body: |
            Review [CHANGELOG](https://github.com/pacoorozco/ssham/blob/main/CHANGELOG.md) to see changes.
