name: Release new version
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${{ github.ref }}" >> "$GITHUB_OUTPUT"

      - name: Build project
        id: build_project
        env:
          DIST_FILE: ./dist/ssham-dist-${{ steps.get_version.outputs.VERSION }}
        run: |
          composer archive --format=zip --file=$DIST_FILE
          echo "DIST_FILE=${DIST_FILE}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ github.ref }}
          artifacts: ${{ steps.build_project.outputs.DIST_FILE }}.zip
          artifactContentType: application/zip
          body: |
            Review [CHANGELOG](https://github.com/pacoorozco/ssham/blob/main/CHANGELOG.md) to see changes.
